server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spa_token_demo}
    username: ${DB_USER:spa_token_demo}
    password: ${DB_PASSWORD:spa-token-demo-lab-2026}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.192.168.50.10.nip.io/realms/myroslava-movchan-lab
          jwk-set-uri: https://keycloak.192.168.50.10.nip.io/realms/myroslava-movchan-lab/protocol/openid-connect/certs

app:
  internal-ca: classpath:internal-ca.pem
